function ExportDataForMapsInitialState(grid, poly, land, initialState, statInitial, data, nameFolder)
% Function that creates the export as csv that can then be imported in R to
% display simulation maps

table_export_simul = table(grid.ID, ...
                     sum(statInitial.householdsIncomeGroup .* data.householdSizeIncomeGroup')', ...
                     sum(initialState.householdsHousingType(:,:))', ...
                     (initialState.householdsHousingType(1,:) + initialState.householdsHousingType(4,:))', ...
                     initialState.householdsHousingType(2,:)', ...
                     initialState.householdsHousingType(3,:)', ...
                     statInitial.averageIncome', ...
                     initialState.dwellingSize(1,:)', ...
                     sum(land.coeffLand)',...
                     land.coeffLandPrivateNoUrbanEdge', ...
                     land.coeffLand(1,:)',...
                     land.coeffLand(2,:)',...
                     land.coeffLand(3,:)',...
                     land.coeffLand(4,:)', ...
                     land.amenities');
table_export_simul.Properties.VariableNames = {'ID_grid' ...
                                         'total_people' ...
                                         'total_households' ...
                                         'total_formal' ...
                                         'total_backyard' ...
                                         'total_settlement' ...
                                         'income' ...
                                         'dwelling_size_formal' ...
                                         'coeff_land_total'...
                                         'coeff_land_formal_noUE',...
                                         'coeff_land_formal'...
                                         'coeff_land_backyard'...
                                         'coeff_land_settlement'...
                                         'coeff_land_RDP', ...
                                         'amenities'};
                                     
                                     
table_export_data = table(grid.ID, ...
                          data.gridNumberPoor' + data.gridNumberRich',...
                          data.gridFormal',...
                          data.gridInformalBackyard',...
                          data.gridInformalSettlement',...
                          data.gridAverageIncome',...
                          sum(land.coeffLand)');
table_export_data.Properties.VariableNames = {'ID_grid' ...
                                         'total_households' ...
                                         'total_formal' ...
                                         'total_backyard' ...
                                         'total_settlement' ...
                                         'income' ...
                                         'coeff_land_total'};

writetable(table_export_simul, strcat('./', nameFolder, '/maps/initial_state_simul.csv'))
writetable(table_export_data, strcat('./', nameFolder, '/maps/initial_state_data_benchmark.csv'))


table_export_jobs = table(poly.xCenter, ...
                          poly.yCenter, ...
                          poly.jobsCenterInit(:,1), ...
                          poly.jobsCenterInit(:,2), ...
                          poly.jobsCenterInit(:,3), ...
                          poly.jobsCenterInit(:,4), ...
                          sum(poly.jobsCenterInit,2));
table_export_jobs.Properties.VariableNames = {'X_center' ...
                                         'Y_center' ...
                                         'jobs1' ...
                                         'jobs2' ...
                                         'jobs3' ...
                                         'jobs4' ...
                                         'total_jobs'};
writetable(table_export_jobs, strcat('./', nameFolder, '/maps/job_centers_simul.csv'))


end
